name: split_flap_display
description: "A high-performance, cinematic split-flap display component for Flutter with realistic procedural sound and responsive layouts."
repository: "https://github.com/luisportal/split_flap_display"
homepage: "https://github.com/luisportal/split_flap_display"
version: 0.1.1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  just_audio_windows: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/flap_single.mp3
    - assets/audio/flap_rain_loop.mp3
